services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  spark-master:
    image: apache/spark:latest
    environment:
      - SPARK_NO_DAEMONIZE=true
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8081:8080"
      - "7077:7077"

  spark-worker:
    image: apache/spark:latest
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
    depends_on:
      - spark-master

  celery-worker:
    build: .
    command: celery -A benchmark_celery worker --concurrency=4 --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis